%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-rmf-dev
Version:        0.0.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmf_dev package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-ament-cmake-catch2
Requires:       ros-iron-menge-vendor
Requires:       ros-iron-nlohmann-json-schema-validator-vendor
Requires:       ros-iron-pybind11-json-vendor
Requires:       ros-iron-rmf-api-msgs
Requires:       ros-iron-rmf-battery
Requires:       ros-iron-rmf-building-map-msgs
Requires:       ros-iron-rmf-building-map-tools
Requires:       ros-iron-rmf-building-sim-common
Requires:       ros-iron-rmf-building-sim-gz-classic-plugins
Requires:       ros-iron-rmf-building-sim-gz-plugins
Requires:       ros-iron-rmf-charger-msgs
Requires:       ros-iron-rmf-dispenser-msgs
Requires:       ros-iron-rmf-door-msgs
Requires:       ros-iron-rmf-fleet-adapter
Requires:       ros-iron-rmf-fleet-adapter-python
Requires:       ros-iron-rmf-fleet-msgs
Requires:       ros-iron-rmf-ingestor-msgs
Requires:       ros-iron-rmf-lift-msgs
Requires:       ros-iron-rmf-obstacle-msgs
Requires:       ros-iron-rmf-robot-sim-common
Requires:       ros-iron-rmf-robot-sim-gz-classic-plugins
Requires:       ros-iron-rmf-robot-sim-gz-plugins
Requires:       ros-iron-rmf-scheduler-msgs
Requires:       ros-iron-rmf-site-map-msgs
Requires:       ros-iron-rmf-task
Requires:       ros-iron-rmf-task-msgs
Requires:       ros-iron-rmf-task-ros2
Requires:       ros-iron-rmf-task-sequence
Requires:       ros-iron-rmf-traffic
Requires:       ros-iron-rmf-traffic-editor
Requires:       ros-iron-rmf-traffic-editor-assets
Requires:       ros-iron-rmf-traffic-editor-test-maps
Requires:       ros-iron-rmf-traffic-examples
Requires:       ros-iron-rmf-traffic-msgs
Requires:       ros-iron-rmf-traffic-ros2
Requires:       ros-iron-rmf-utils
Requires:       ros-iron-rmf-visualization
Requires:       ros-iron-rmf-visualization-building-systems
Requires:       ros-iron-rmf-visualization-fleet-states
Requires:       ros-iron-rmf-visualization-floorplans
Requires:       ros-iron-rmf-visualization-msgs
Requires:       ros-iron-rmf-visualization-navgraphs
Requires:       ros-iron-rmf-visualization-obstacles
Requires:       ros-iron-rmf-visualization-rviz2-plugins
Requires:       ros-iron-rmf-visualization-schedule
Requires:       ros-iron-rmf-websocket
Requires:       ros-iron-rmf-workcell-msgs
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A package to aggregate the packages required for a minimal installation of Open-
RMF

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Fri Jun 09 2023 Yadunund <yadunund@openrobotics.org> - 0.0.1-1
- Autogenerated by Bloom

